---
title: "Data_Cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(tidyr)
library(zoo)
```



```{r}
#grad_rate = read.csv("graduation_rate.csv") #a lot of missing data
employ_rate = read.csv("employment_rate.csv")
wage_gap = read.csv("Gender_wage_gap.csv")
```

```{r}
employ_rate$TIME <- as.numeric(as.character(employ_rate$TIME))
employ_rate <-
  employ_rate %>%
  filter(!grepl('-', TIME)) %>%
  filter(grepl('PC_WKGPOP', MEASURE)) %>%
  filter(TIME >= 2000) %>%
  filter(TIME <= 2014) %>%
  filter(LOCATION != "OECD", LOCATION != "EU28", LOCATION != "G-7",  LOCATION != "EA19")%>%
  filter(LOCATION != 'LTU', LOCATION != 'CRI')


employ_rate <-
  employ_rate %>%
  spread(SUBJECT, Value) %>%
  mutate(Value = (1-(WOMEN/MEN))*100) %>%
  select(LOCATION, TIME, Value) %>%
  left_join(country_codes, by = c("LOCATION" = "CODE"))

employ_rate_avg <- 
  employ_rate %>%
  group_by(TIME)%>%
  summarize(Value=mean(Value)) %>%
  mutate(LOCATION = "WRD") %>%
  mutate(Country = "World Average") %>%
  select(LOCATION, TIME, Value, Country)
```
```{r}
employ_rate_final <- rbind(employ_rate, employ_rate_avg)  
   # filter(TIME >= 2005)
#employ_rate$TIME <- as.factor(employ_rate$TIME)

```


```{r}

write.csv(employ_rate_final, "employ_rate_final.csv")
```

```{r}

wage_gap$TIME <- as.numeric(as.character(wage_gap$TIME))
wage_gap <-
  wage_gap %>%
  filter(SUBJECT == 'TOT') %>%
  filter(LOCATION != 'EU28') %>%
  filter(LOCATION != 'LTU') %>%
  filter(LOCATION != 'CRI') %>%
  filter(TIME >= 2000) %>%
  filter(TIME <= 2014)

wage_gap_avg <- 
wage_gap %>%
  group_by(TIME)%>%
  summarize(Value=mean(Value)) %>%
  mutate(LOCATION = "WRD") %>%
  mutate(Country = "World Average") %>%
  select(LOCATION, TIME, Value, Country)

#wage_gap$TIME <- as.factor(wage_gap$TIME)
#write.csv( wage_gap,"wagegap_only.csv")
```

```{r}
all_tables <- rbind(employ_rate, wage_gap) #,grad_rate)
colnames(all_tables)[1] <- "LOCATION"
write.csv(all_tables, "final_table.csv")

```

```{r}
#To get info for a single county. Change the string inside grepl for for the
# country abreviation to get the data for a particular country
single_country <- 
  all_tables %>%
  filter(grepl('CAN', LOCATION))

write.csv( single_country,"canada_only.csv")

```

```{r}

country_codes <- read.csv("FinalProjectD3/src/data/country_codes.csv")
   
 

```

```{r}

country_codes <- 
  country_codes %>%
  select('CODE', 'Country')
   

```

```{r}

wage_gap <- 
  wage_gap %>%
  left_join(country_codes, by = c("LOCATION" = "CODE"))
```
```{r}
wage_gap <-
  wage_gap %>%
  select(LOCATION, TIME, Value, Country)
   

```
```{r}
wage_gap_final = rbind(wage_gap, wage_gap_avg)
```
```{r}
write.csv( wage_gap_final,"wagegap_only.csv")
```

```{r}
joint_data2 <-
  wage_gap %>%
  full_join(employ_rate) %>%
  arrange(LOCATION, TIME)
```


```{r}
write.csv(joint_data2, "employ_wage_data2.csv")
```

```{r}
emp_rat = which(is.na(joint_data2$genderDiff))
joint_data2$genderDiff[emp_rat] <- sapply(emp_rat, function(i) with(joint_data2, mean(c(genderDiff[i-1], genderDiff[i+1]))) )
```

```{r}
emp_rat = which(is.na(joint_data2$genderDiff))
joint_data2$genderDiff[emp_rat] = na.approx(joint_data2$genderDiff)

```
```{r}
write.csv(joint_data2, "employ_wage_data2.csv")
```

```{r}
employ_rate_final_rank<-
  employ_rate %>% 
  spread(TIME, Value, fill = NA, convert = FALSE)
```

```{r}
employ_rate_final_rank<-
  employ_rate %>% 
  spread(TIME, Value, fill = NA, convert = FALSE)
```

```{r}
write.csv(employ_rate_final_rank, "employ_rate_final_rank.csv")
```
